# Generated by Django 2.2.5 on 2020-03-19 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
